In [29]:
import pandas as pd
from pathlib import Path # importing files
from pyzillow.pyzillow import ZillowWrapper, GetDeepSearchResults # Zillow information

Austin counties: Hays, Travis, Williamson
78610, 78613, 78617, 78641, 78652, 78653, 78660, 78664, 78681, 78701, 78702, 78703, 78704, 78705, 78712, -78717-, 78719, 78721, 78722, 78723, 78724, 78725, 78726, 78727, 78728, 78729, 78730, 78731, 78732, 78733, 78734, 78735, 78736, 78737, 78738, 78739, 78741, 78742, 78744, 78745, 78746, 78747, 78748, 78749, 78750, 78751, 78752, 78753, 78754, 78756, 78757, 78758, 78759.



Cedar Park: Williamson 78613, Travis
Leander: Williamson 78641, Travis
RR - Williamson 78664 , Travis
georgetown  78626, 78628, 78633, 78665.

# Travis County

In [176]:
list_df = []
folder="Desktop/Zillow Data/Zip/Tra/"
for file in Path(folder).glob('*.csv'):
    df = pd.read_csv(file)
    list_df.append(df)
df_tra = pd.concat(list_df)

In [177]:
df_tra

,Property ID,Geographic ID,Type,Property Address,Legal Description,Owner Name,Doing Business As,Appraised Value
0,584968,0239720305,Real,12916 JAMES MADISON ST TX 78653,LOT 35 BLK O PRESIDENTIAL MEADOWS SEC 2,CALZADILLA JOSE LUIS RODRIGUEZ,NaN,"177,203"
1,240961,0237720101,Real,13004 ARMSTRONG LN TX 78653,ABS 315 SUR 63 GATES G ACR 0.7702,1-40 GROUP,NaN,"83,878"
2,862578,NaN,Personal,"11923 E U S HY 290 MANOR, TX 78653",PERSONAL PROPERTY COMMERCIAL 101 PARK AVENUE P...,101 PARK AVENUE PARTNERS INC,101 PARK AVENUE PARTNERS INC,609
3,525821,0227670202,Real,11712 BRIARCREEK LOOP TX 78653,LOT 10 BLK B BRIARCREEK SUBD SEC 1,101 VENTURES LLC,NaN,"139,879"
4,546304,0227670114,Real,12104 LIMA DR TX 78653,LOT 26 BLK E BRIARCREEK SUBD SEC 2,101 VENTURES LLC,NaN,"160,422"
...,...,...,...,...,...,...,...,...
2621,281145,2.82301e+08,Real,17018 JIGSAW PATHWAY TX 78664,LOT 51 BLK M SPRINGBROOK CENTRE PHS A,ZHU QIANG & YAN LIU,NaN,"239,350"
2622,894543,2.86361e+08,Real,2812 BRIDEKIRK DR TX 78664,LOT 10 BLK F GLEN ELLYN SEC 1,ZHU XINMIN & FAN WANG,NaN,"218,592"
2623,482133,2.84301e+08,Real,1600 BALMORHEA LN TX 78664,LOT 13 BLK F CAMBRIDGE HEIGHTS PHS A SEC 2,ZIPP SHERRY,NaN,"242,546"
2624,371365,2.9348e+08,Real,1349 AMISTAD DR TX 78664,LOT 26 HUNTINGTON TRAILS,ZOCH RICHARD,NaN,"285,012"
2625,482196,2.8433e+08,Real,17603 FORT LEATON DR TX 78664,LOT 32 BLK B CAMBRIDGE HEIGHTS PHS A SEC 1-B,ZURITA SERGIO & ADELA VALADEZ,NaN,"192,861"

# Cleaning Travis County Dataset

First I need to remove buisnesses from my dataset

In [178]:
df_tra['company']=df_tra['Owner Name'].apply(lambda x: 1 if 'LLC' in x else 0) # dummy variable
df_tra = df_tra[df_tra.company==0] 
df_tra['company_1']=df_tra['Owner Name'].apply(lambda x: 1 if any(i.isdigit() for i in x) else 0) # dummy variable
df_tra = df_tra[df_tra.company_1==0]

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [179]:
df_tra

,Property ID,Geographic ID,Type,Property Address,Legal Description,Owner Name,Doing Business As,Appraised Value,company,company_1
0,584968,0239720305,Real,12916 JAMES MADISON ST TX 78653,LOT 35 BLK O PRESIDENTIAL MEADOWS SEC 2,CALZADILLA JOSE LUIS RODRIGUEZ,NaN,"177,203",0,0
117,839808,NaN,Personal,13419 E U S HY 290 11-C TX 78653,PERSONAL PROPERTY COMMERCIAL A PRIME MEDICAL H...,A PRIME MEDICAL HOME HEALTH INC,A PRIME MEDICAL HOME HEALTH INC,"18,283",0,0
119,238594,0235590605,Real,EGGLESTON ST TX 78653,LOT 5 BLK 46 MANOR TOWN OF,AAA FIRE & SAFETY EQUIPMENT CO INC,NaN,"35,000",0,0
120,910140,NaN,Personal,"15105 E U S HY 290 MANOR, TX 78653",PERSONAL PROPERTY COMMERCIAL AAA STORAGE,AAA STORAGE,AAA STORAGE,0,0,0
121,730024,0241720110,Real,"13617 RICHARD NIXON ST MANOR, TX 78653",LOT 56 BLK H PRESIDENTIAL MEADOWS SEC 4,AALBERS JOAN & GERALD,NaN,"203,999",0,0
...,...,...,...,...,...,...,...,...,...,...
2621,281145,2.82301e+08,Real,17018 JIGSAW PATHWAY TX 78664,LOT 51 BLK M SPRINGBROOK CENTRE PHS A,ZHU QIANG & YAN LIU,NaN,"239,350",0,0
2622,894543,2.86361e+08,Real,2812 BRIDEKIRK DR TX 78664,LOT 10 BLK F GLEN ELLYN SEC 1,ZHU XINMIN & FAN WANG,NaN,"218,592",0,0
2623,482133,2.84301e+08,Real,1600 BALMORHEA LN TX 78664,LOT 13 BLK F CAMBRIDGE HEIGHTS PHS A SEC 2,ZIPP SHERRY,NaN,"242,546",0,0
2624,371365,2.9348e+08,Real,1349 AMISTAD DR TX 78664,LOT 26 HUNTINGTON TRAILS,ZOCH RICHARD,NaN,"285,012",0,0
2625,482196,2.8433e+08,Real,17603 FORT LEATON DR TX 78664,LOT 32 BLK B CAMBRIDGE HEIGHTS PHS A SEC 1-B,ZURITA SERGIO & ADELA VALADEZ,NaN,"192,861",0,0

Now will delete all "personal" type of property

In [180]:
df_tra = df_tra[df_tra.Type=='Real'] 
del df_tra['company']
del df_tra['company_1']
del df_tra['Geographic ID']
del df_tra['Property ID']
del df_tra['Type']
del df_tra['Legal Description']
del df_tra['Owner Name']
del df_tra['Doing Business As']

In [182]:
list_zips = []
for row_index, row  in df_tra['Property Address'].iteritems():
    
    zipcode = row.split()[-1][:5]
    list_zips.append(zipcode)

In [183]:
df_tra['zipcodes'] = list_zips

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [184]:
list_addresses = []
for row_index, row  in df_tra['Property Address'].iteritems():

    address = ' '.join(row.split()[:-1])
    list_addresses.append(address)

In [185]:
df_tra['Address'] = list_addresses

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [186]:
del df_tra['Property Address']
df_tra = df_tra.reset_index()
df_tra = df_tra.drop_duplicates(subset='Address', keep='first')

In [188]:
df_tra.zipcodes.unique()

array(['78653', '78746', '78669', '78747', '78610', '78660', '78704',
       '78749', '78652', '78641', '78748', '78745', '78752', '78734',
       '78759', '78645', '78753', '78758', '78617', '78621', '78751',
       '78750', '78757', '78613', '78742', '78735', '78727', '78726',
       '78741', '78724', '78738', '78739', '78725', '78729', '78723',
       '78722', '78728', '78736', '78730', '78731', '78737', '78719',
       '78721', '78733', '78712', '78705', '78732', '78701', '78744',
       '78702', '78703', '78756', '78754', '78681', '78664'], dtype=object)

In [189]:
df_tra.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 312927 entries, 0 to 328643
Data columns (total 4 columns):
index              312927 non-null int64
Appraised Value    312927 non-null object
zipcodes           312927 non-null object
Address            312927 non-null object
dtypes: int64(1), object(3)
memory usage: 11.9+ MB

In [25]:
df_tra['Address'] = df_tra['Address'].str.strip()

In [193]:
df_tra[df_tra['Address'] == '21339 BLAKE-MANOR RD TX']

   index Appraised Value zipcodes                  Address
4    123         210,457    78653  21339 BLAKE-MANOR RD TX

In [194]:
df_tra.to_csv('df_travis.csv')

address = '2207 Kerr trl, Cedar Park, TX'
zipcode = '78613'
zillow_data = ZillowWrapper('X1-ZWz1hfzyp0bf2j_1hdll')
deep_search_response = zillow_data.get_deep_search_results(address,zipcode)
result = GetDeepSearchResults(deep_search_response)
home_type_3189_4190.append(result.home_type)
year_built_3189_4190.append(result.year_built)
home_size_3189_4190.append(result.home_size)
bathrooms_3189_4190.append(result.bathrooms)
bedrooms_3189_4190.append(result.bedrooms)
last_sold_date_0_1000.append(result.last_sold_date)
last_sold_price_0_1000.append(result.last_sold_price)
latitude_0_1000.append(result.latitude)
longitude_0_1000.append(result.longitude)
zestimate_amount_0_1000.append(result.zestimate_amount)

year_built_3189_4190

In [30]:
home_type_3189_4190 = []
year_built_3189_4190 = []
home_size_3189_4190 = []
bathrooms_3189_4190 = []
bedrooms_3189_4190 = []
last_sold_date_3189_4190 = []
last_sold_price_3189_4190 = []
latitude_3189_4190 = []
longitude_3189_4190  = []
zestimate_amount_3189_4190 = []


'''num_floors
parking_type
heating_sources
heating_system
neighborhood
school_district'''

'num_floors\nparking_type\nheating_sources\nheating_system\nneighborhood\nschool_district'

In [38]:
df_tra.head()

   index Appraised Value    Zip                          Address
0      0         177,203  78653        12916 JAMES MADISON ST TX
1    119          35,000  78653                  EGGLESTON ST TX
2    121         203,999  78653  13617 RICHARD NIXON ST MANOR TX
3    122         228,677  78653          18905 GREAT FALLS DR TX
4    123         210,457  78653          21339 BLAKE-MANOR RD TX

# Williamson County

In [ ]:
list_df_wil = []
folder="Desktop/Zillow Data/Zip/Wil/"
for file in Path(folder).glob('*.csv'):
    df = pd.read_csv(file)
    list_df_wil.append(df)
    
df_wil = pd.concat(list_df)
df_wil